#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# BatteryLab one-click runner for recipe batch: idx-0.1_20260702_214147
# Auto-generated by BL-deploy/generate_run.py -- DO NOT hand-edit.
# Self-contained (stdlib only). Drop anywhere on rasp5-hobbs and run.
#
# What it does: brings up the 3 ROS2 services, waits for readiness, then
# drives `ros2 run assembly_robot app` through [B]atch -> assemble, feeding
# the embedded recipe below. Full log written next to this file.

# The CONFIG/RECIPES blocks below are verbatim JSON snapshots; map JSON
# literals to Python so the embedded blocks parse (fixes NameError: 'true').
true, false, null = True, False, None

CONFIG = {
  "_comment": "Lab topology + environment for the BatteryLab one-click runner. This is the ONLY place with machine-specific details. Verify every value against the actual rasp5-hobbs setup before the first real run. The runner that generate_run.py produces embeds a snapshot of this file, so re-generate after editing.",
  "env_setup": "~/.ros_env_setup.sh",
  "_env_setup_note": "Sourced before every ros2 command (local and remote). This is the lab's canonical bootstrap that batterylab.launch.py already uses on remotes; it should put ros2 on PATH, activate lab_venv, and source the ros2_ws install/ overlay so 'battery_lab_bringup' and 'assembly_robot' resolve. If your setup uses different files, either edit that script or list them in extra_source below.",
  "extra_source": [],
  "ros_domain_id": "42",
  "launches": [
    {
      "role": "out",
      "host": "local",
      "cmd": "ros2 launch battery_lab_bringup out_rasp.launch.py"
    },
    {
      "role": "rail",
      "host": "rasp4",
      "cmd": "ros2 launch battery_lab_bringup rail_rasp.launch.py"
    },
    {
      "role": "board",
      "host": "rasp5",
      "cmd": "ros2 launch battery_lab_bringup board_rasp.launch.py"
    }
  ],
  "_launches_note": "host 'local' runs on this machine (rasp5-hobbs). Other hosts are passed to `ssh <host> ...`; they must be passwordless SSH aliases resolvable from rasp5-hobbs (as in the manual 'ssh rasp4 ...' instructions).",
  "readiness_nodes": [
    "tower_usb_cam",
    "rail_meca500_camera_server",
    "suction_pump_server",
    "linear_rail_server",
    "look_up_camera_server",
    "sartorius_dispensing_server"
  ],
  "_readiness_note": "The runner polls `ros2 node list` until all of these appear (or node_wait_timeout_s elapses). Names come straight from the *.launch.py files. If a node fails to appear the runner warns but still lets you proceed.",
  "app_cmd": "ros2 run assembly_robot app",
  "remote_recipe_dir": "~/.batterylab",
  "_remote_recipe_note": "Where the runner writes the embedded recipe JSON on this machine before feeding its path to the app's [B]atch loader.",
  "inventory_file": "~/.batterylab/electrolyte_inventory.json",
  "inventory_check": "strict",
  "_inventory_note": "Preflight: before launching anything, verify every solvent/salt each recipe needs exists in the robot's vial inventory (the same stock the app's formulation solver draws from). A missing component is exactly what produces 'Error resolving required volumes: No optimal solution found' in the [B]atch loader. Modes: 'strict' = abort the run before ROS bringup; 'warn' = log and continue; 'off' = skip.",
  "inventory_aliases": {},
  "_inventory_aliases_note": "Optional name mapping if recipes and inventory spell a chemical differently, e.g. {\"DMSO\": \"dimethyl sulfoxide\"}. Matching is case/whitespace-insensitive already.",
  "action": "test",
  "_action_note": "assemble = drive straight to [A]ssemble now. Set to 'test' to stop after the text simulation (dry run, no hardware motion) \u2014 useful for a first smoke test.",
  "metadata": "auto",
  "_metadata_note": "auto = reuse saved batch-component metadata when the app offers it ('yEs!'), otherwise accept blank component details on a first run. This keeps the run unattended; edit the app's saved metadata separately if you need real lot/supplier fields.",
  "timings": {
    "node_wait_timeout_s": 90,
    "startup_settle_s": 8,
    "app_menu_timeout_s": 300,
    "assembly_timeout_s": 21600
  },
  "_timings_note": "assembly_timeout_s (default 6 h) is the max wall-clock to wait for a whole batch to finish once assembly starts; raise it for large batches. app_menu_timeout_s is per-prompt (covers robot homing/vision before the first menu appears)."
}

RECIPE_STEM = "idx-0.1_20260702_214147"

RECIPES = [
  {
    "recipe_name": "aw_dmso_w02",
    "target_electrolyte": {
      "name": "aw_target_dmso_w02",
      "volume": 0.05,
      "v": {
        "water": 0.02,
        "dimethyl sulfoxide": 0.98
      },
      "s": {
        "TBAClO4": 0.1
      },
      "local_smiles": {
        "water": "O",
        "dimethyl sulfoxide": "CS(=O)C"
      },
      "use_pubchem": true
    }
  },
  {
    "recipe_name": "aw_dmso_w05",
    "target_electrolyte": {
      "name": "aw_target_dmso_w05",
      "volume": 0.05,
      "v": {
        "water": 0.05,
        "dimethyl sulfoxide": 0.95
      },
      "s": {
        "TBAClO4": 0.1
      },
      "local_smiles": {
        "water": "O",
        "dimethyl sulfoxide": "CS(=O)C"
      },
      "use_pubchem": true
    }
  },
  {
    "recipe_name": "aw_dmso_w10",
    "target_electrolyte": {
      "name": "aw_target_dmso_w10",
      "volume": 0.05,
      "v": {
        "water": 0.1,
        "dimethyl sulfoxide": 0.9
      },
      "s": {
        "TBAClO4": 0.1
      },
      "local_smiles": {
        "water": "O",
        "dimethyl sulfoxide": "CS(=O)C"
      },
      "use_pubchem": true
    }
  },
  {
    "recipe_name": "aw_dmso_w20",
    "target_electrolyte": {
      "name": "aw_target_dmso_w20",
      "volume": 0.05,
      "v": {
        "water": 0.2,
        "dimethyl sulfoxide": 0.8
      },
      "s": {
        "TBAClO4": 0.1
      },
      "local_smiles": {
        "water": "O",
        "dimethyl sulfoxide": "CS(=O)C"
      },
      "use_pubchem": true
    }
  },
  {
    "recipe_name": "aw_dmf_w10",
    "target_electrolyte": {
      "name": "aw_target_dmf_w10",
      "volume": 0.05,
      "v": {
        "water": 0.1,
        "N,N-dimethylformamide": 0.9
      },
      "s": {
        "TBAClO4": 0.1
      },
      "local_smiles": {
        "water": "O",
        "N,N-dimethylformamide": "CN(C)C=O"
      },
      "use_pubchem": true
    }
  },
  {
    "recipe_name": "aw_pc_w10",
    "target_electrolyte": {
      "name": "aw_target_pc_w10",
      "volume": 0.05,
      "v": {
        "water": 0.1,
        "propylene carbonate": 0.9
      },
      "s": {
        "TBAClO4": 0.1
      },
      "local_smiles": {
        "water": "O",
        "propylene carbonate": "CC1COC(=O)O1"
      },
      "use_pubchem": true
    }
  },
  {
    "recipe_name": "aw_tms_w10",
    "target_electrolyte": {
      "name": "aw_target_tms_w10",
      "volume": 0.05,
      "v": {
        "water": 0.1,
        "sulfolane": 0.9
      },
      "s": {
        "TBAClO4": 0.1
      },
      "local_smiles": {
        "water": "O",
        "sulfolane": "O=S1(=O)CCCC1"
      },
      "use_pubchem": true
    }
  },
  {
    "recipe_name": "aw_acn_w10",
    "target_electrolyte": {
      "name": "aw_target_acn_w10",
      "volume": 0.05,
      "v": {
        "water": 0.1,
        "acetonitrile": 0.9
      },
      "s": {
        "TBAClO4": 0.1
      },
      "local_smiles": {
        "water": "O",
        "acetonitrile": "CC#N"
      },
      "use_pubchem": true
    }
  },
  {
    "recipe_name": "aw_acn_w05",
    "target_electrolyte": {
      "name": "aw_target_acn_w05",
      "volume": 0.05,
      "v": {
        "water": 0.05,
        "acetonitrile": 0.95
      },
      "s": {
        "TBAClO4": 0.1
      },
      "local_smiles": {
        "water": "O",
        "acetonitrile": "CC#N"
      },
      "use_pubchem": true
    }
  }
]


import atexit
import json
import os
import pty
import re
import select
import signal
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

RUN_DIR = Path(__file__).resolve().parent
LOG_DIR = RUN_DIR / ("batterylab_run_%s_%s" % (RECIPE_STEM, datetime.now().strftime("%Y%m%d_%H%M%S")))
LOG_DIR.mkdir(parents=True, exist_ok=True)
MAIN_LOG = open(LOG_DIR / "runner.log", "a", buffering=1, encoding="utf-8")


def log(msg):
    line = "[%s] %s" % (datetime.now().strftime("%H:%M:%S"), msg)
    print(line, flush=True)
    MAIN_LOG.write(line + "\n")


def expand(p):
    return os.path.expanduser(str(p))


def env_prefix():
    """Shell snippet that reproduces the operator's ROS env for a non-interactive
    (double-clicked) process: source the lab bootstrap, any extras, set domain id."""
    parts = ["source %s" % expand(CONFIG["env_setup"])]
    for extra in CONFIG.get("extra_source", []):
        parts.append("source %s" % expand(extra))
    parts.append("export ROS_DOMAIN_ID=%s" % CONFIG["ros_domain_id"])
    return " && ".join(parts)


def bash_c(inner):
    """Run `inner` in a login bash with the ROS env sourced. Returns argv list."""
    return ["bash", "-lc", "%s && %s" % (env_prefix(), inner)]


PROCS = []  # (name, Popen)


def _terminate_all():
    for name, p in PROCS:
        if p.poll() is None:
            try:
                os.killpg(os.getpgid(p.pid), signal.SIGINT)
            except Exception:
                try:
                    p.terminate()
                except Exception:
                    pass
    time.sleep(2)
    for name, p in PROCS:
        if p.poll() is None:
            try:
                os.killpg(os.getpgid(p.pid), signal.SIGKILL)
            except Exception:
                try:
                    p.kill()
                except Exception:
                    pass


atexit.register(_terminate_all)


def start_launch(role, host, cmd):
    logf = open(LOG_DIR / ("launch_%s.log" % role), "a", buffering=1, encoding="utf-8")
    if host == "local":
        argv = bash_c(cmd)
    else:
        # Mirror the lab's own remote-launch pattern: -t for a tty so Ctrl-C/EXIT
        # propagates, and a trap so killing ssh tears down the remote node group.
        remote = "%s && trap 'kill 0' SIGINT EXIT && %s" % (env_prefix(), cmd)
        argv = ["ssh", "-tt", host, "bash -lc %s" % _shquote(remote)]
    log("starting [%s] on %s: %s" % (role, host, cmd))
    p = subprocess.Popen(
        argv, stdout=logf, stderr=subprocess.STDOUT,
        stdin=subprocess.DEVNULL, start_new_session=True,
    )
    PROCS.append((role, p))
    return p


def _shquote(s):
    return "'" + s.replace("'", "'\\''") + "'"


def wait_for_nodes():
    want = set(CONFIG.get("readiness_nodes", []))
    if not want:
        return
    timeout = CONFIG["timings"]["node_wait_timeout_s"]
    log("waiting up to %ss for nodes: %s" % (timeout, ", ".join(sorted(want))))
    deadline = time.time() + timeout
    seen = set()
    while time.time() < deadline:
        for role, p in PROCS:
            if p.poll() is not None:
                log("WARNING: launch [%s] exited early (code %s) -- see its log" % (role, p.returncode))
        try:
            out = subprocess.run(
                bash_c("ros2 node list"),
                capture_output=True, text=True, timeout=15,
            ).stdout
        except Exception as e:
            out = ""
            log("ros2 node list failed: %s" % e)
        present = {ln.strip().lstrip("/") for ln in out.splitlines() if ln.strip()}
        seen = {w for w in want if any(w in n for n in present)}
        if want <= seen:
            log("all expected nodes are up.")
            break
        time.sleep(3)
    else:
        missing = want - seen
        log("WARNING: nodes still missing after %ss: %s" % (timeout, ", ".join(sorted(missing))))
        log("         proceeding anyway; the app may error if a service is truly down.")
    settle = CONFIG["timings"]["startup_settle_s"]
    log("settling for %ss before starting the app..." % settle)
    time.sleep(settle)


def write_recipe():
    d = Path(expand(CONFIG["remote_recipe_dir"]))
    d.mkdir(parents=True, exist_ok=True)
    path = d / ("%s.json" % RECIPE_STEM)
    path.write_text(json.dumps(RECIPES, indent=2), encoding="utf-8")
    log("wrote recipe (%d cell(s)) to %s" % (len(RECIPES), path))
    return path


# --------------------------------------------------------------------------- #
# Inventory preflight: recipes vs the robot's electrolyte vial stock.          #
# --------------------------------------------------------------------------- #
def _norm(name):
    return re.sub(r"\s+", " ", str(name)).strip().lower()


def check_inventory():
    """Verify every component (solvent + salt) each recipe needs is present in
    the vial inventory JSON that the app's formulation solver draws from.
    Missing components are what cause the [B]atch loader to fail with
    'Error resolving required volumes: No optimal solution found' (and then
    trip the app's own error-path bug: 'FormulationPlan' has no attribute 'get').
    Returns True if the run may proceed."""
    mode = CONFIG.get("inventory_check", "strict")
    if mode == "off":
        return True

    inv_path = Path(expand(CONFIG.get("inventory_file", "~/.batterylab/electrolyte_inventory.json")))
    if not inv_path.exists():
        log("WARNING: inventory file not found: %s (skipping preflight)" % inv_path)
        return mode != "strict"
    try:
        inv = json.loads(inv_path.read_text(encoding="utf-8"))
    except Exception as e:
        log("WARNING: could not parse inventory %s: %s" % (inv_path, e))
        return mode != "strict"

    aliases = {_norm(k): _norm(v) for k, v in CONFIG.get("inventory_aliases", {}).items()}

    def canon(n):
        n = _norm(n)
        return aliases.get(n, n)

    pure_solvents = set()   # available as a pure, salt-free stock (fraction 1.0)
    solvents_any = set()    # present in at least one usable vial (possibly salted/mixed)
    salts_any = set()       # salts present in at least one usable vial
    stock_lines, low_lines = [], []

    for vial in inv.get("vials", []):
        cur = vial.get("current_electrolyte") or {}
        vol = float(vial.get("volume_ul") or 0)
        thr = float(vial.get("low_volume_threshold_ul") or 0)
        loc = "(%s,%s)" % (vial.get("x_ind"), vial.get("y_ind"))
        name = cur.get("name", "?")
        if not cur:
            low_lines.append("%s: empty slot" % loc)
            continue
        if vol <= thr:
            low_lines.append("%s '%s': %.0f uL (at/below threshold %.0f uL) -- ignored"
                             % (loc, name, vol, thr))
            continue
        v = {canon(k): float(x) for k, x in (cur.get("v") or {}).items()}
        s = {canon(k): float(x) for k, x in (cur.get("s") or {}).items()}
        solvents_any |= set(v)
        salts_any |= set(s)
        if not s and len(v) == 1 and abs(next(iter(v.values())) - 1.0) < 1e-6:
            pure_solvents |= set(v)
        stock_lines.append("%s '%s': %.0f uL  solvents=%s  salts=%s"
                           % (loc, name, vol, sorted(v), sorted(s)))

    log("--- inventory preflight: %s ---" % inv_path)
    for ln in stock_lines:
        log("  stock %s" % ln)
    for ln in low_lines:
        log("  LOW   %s" % ln)

    problems, notes = [], []
    demand = {}  # per-solvent requested volume, in the recipes' own volume units
    for rec in RECIPES:
        t = rec.get("target_electrolyte", {})
        rname = rec.get("recipe_name", t.get("name", "?"))
        need_solv = {canon(k): float(x) for k, x in (t.get("v") or {}).items()}
        need_salt = {canon(k) for k in (t.get("s") or {})}
        for k, frac in need_solv.items():
            demand[k] = demand.get(k, 0.0) + frac * float(t.get("volume") or 0)
        missing_solv = set(need_solv) - solvents_any
        missing_salt = need_salt - salts_any
        if missing_solv or missing_salt:
            problems.append("recipe '%s': missing solvents=%s salts=%s"
                            % (rname, sorted(missing_solv), sorted(missing_salt)))
        else:
            impure_only = (set(need_solv) & solvents_any) - pure_solvents
            if impure_only:
                notes.append("recipe '%s': solvents %s only stocked mixed with salts; "
                             "the solver may still fail to hit the target composition"
                             % (rname, sorted(impure_only)))

    if demand:
        log("  total requested volume per solvent (recipe units): %s"
            % ", ".join("%s=%.3g" % (k, v) for k, v in sorted(demand.items())))
    for n in notes:
        log("  note: %s" % n)

    if problems:
        log("INVENTORY CHECK FAILED -- the [B]atch solver would report 'No optimal solution found':")
        for p in problems:
            log("  " + p)
        log("Fix: stock the missing chemicals via the app's [E]lectrolyte vial manager")
        log("     (which updates %s), or regenerate this runner" % inv_path)
        log("     with recipes that match the current stock.")
        if mode == "strict":
            log("Aborting before ROS bringup. (Set CONFIG['inventory_check']='warn' to override.)")
            return False
        log("inventory_check='warn': continuing anyway -- expect the batch load to fail.")
        return True

    log("inventory preflight OK: every recipe component is in stock.")
    return True


# --------------------------------------------------------------------------- #
# The pty-driven "expect" state machine for `ros2 run assembly_robot app`.      #
# --------------------------------------------------------------------------- #
def drive_app(recipe_path):
    action = CONFIG.get("action", "assemble")
    app_log = open(LOG_DIR / "app.log", "a", buffering=1, encoding="utf-8")

    argv = bash_c(CONFIG["app_cmd"])
    log("starting app: %s" % CONFIG["app_cmd"])
    pid, fd = pty.fork()
    if pid == 0:  # child
        os.execvp(argv[0], argv)
        os._exit(127)

    # Phases: 0=need to open [B]atch, 1=in batch dialog, 2=assembly running/done.
    phase = 0
    started_assembly = False
    batch_failed = False
    buf = ""
    per_prompt_timeout = CONFIG["timings"]["app_menu_timeout_s"]
    assembly_timeout = CONFIG["timings"]["assembly_timeout_s"]
    last_activity = time.time()

    def send(s, echo=None):
        os.write(fd, (s + "\n").encode())
        log("  -> sent: %s" % (echo if echo is not None else repr(s)))

    def consume_prompt():
        # Drop matched text so we don't re-trigger on the same prompt.
        nonlocal buf
        buf = ""

    try:
        while True:
            timeout = assembly_timeout if phase == 2 else per_prompt_timeout
            if time.time() - last_activity > timeout:
                log("TIMEOUT after %ss with no matching prompt (phase %d)." % (timeout, phase))
                log("Last output tail:\n%s" % buf[-800:])
                raise TimeoutError("app did not reach expected state")

            r, _, _ = select.select([fd], [], [], 5)
            if not r:
                continue
            try:
                chunk = os.read(fd, 4096)
            except OSError:
                chunk = b""
            if not chunk:
                log("app process closed its output stream.")
                break
            last_activity = time.time()
            text = chunk.decode(errors="replace")
            sys.stdout.write(text)
            sys.stdout.flush()
            app_log.write(text)
            buf += text
            # Keep the tail bounded but large enough to hold a full prompt.
            if len(buf) > 8000:
                buf = buf[-8000:]

            low = buf.lower()

            # --- completion markers (check first so we quit cleanly) ---
            if started_assembly and phase == 2 and (
                "completed batch assembly of" in low
                or "assembly completed. success record" in low
            ):
                log("batch assembly reported complete.")
                # fall through: next main-menu prompt -> quit

            # --- prompt handlers ---
            # component-counter config reuse prompt (appears during app init,
            # before the main menu) -> accept the existing counts (default Yes)
            if "do you want to use the existing config" in low:
                send("", echo="[Enter] use existing config")
                consume_prompt()
                continue

            if phase == 0 and ":>" in buf:
                # main menu
                send("b", echo="[B]atch")
                phase = 1
                consume_prompt()
                continue

            # batch load/assessment failure (e.g. recipe needs a chemical that
            # isn't in the vial inventory -> 'No optimal solution found').
            # Do NOT consume the buffer: the main menu often arrives in the
            # same chunk, and the next handler needs to see it.
            if phase == 1 and not batch_failed and (
                "no optimal solution found" in low
                or "failed to assess recipes" in low
                or "error resolving required volumes" in low
            ):
                log("!! app could not plan the batch from current inventory.")
                batch_failed = True
                # fall through -- quit at the next main-menu prompt

            if batch_failed and ":>" in buf and "welcome to batterylab" in low:
                send("", echo="[Enter] quit (batch load failed)")
                raise RuntimeError(
                    "batch assessment failed: recipe components not satisfiable "
                    "from electrolyte inventory -- see log and run the inventory "
                    "preflight output above")

            if phase == 1 and "enter path to recipes json file" in low:
                send(str(recipe_path), echo=str(recipe_path))
                consume_prompt()
                continue

            if phase == 1 and "choose action:" in low:
                if action == "test":
                    send("t", echo="[T]est (dry run)")
                    # after the text sim the app asks: "Proceed to assemble ... (y/n)"
                elif action == "assemble":
                    send("a", echo="[A]ssemble now")
                    started_assembly = True
                    phase = 2
                else:
                    send("c", echo="[C]ancel")
                consume_prompt()
                continue

            if phase == 1 and "proceed to assemble these recipes now?" in low:
                if action == "assemble":
                    send("y", echo="y")
                    started_assembly = True
                    phase = 2
                else:
                    send("n", echo="n (dry run only)")
                    phase = 2  # nothing more to do; will hit menu and quit
                consume_prompt()
                continue

            # metadata: reuse branch (exact 'yEs!' required by the app)
            if "to reuse this metadata" in low:
                send("yEs!", echo='yEs! (reuse metadata)')
                consume_prompt()
                continue

            # metadata: fresh branch -> accept blank component details
            if "details (material / lot / supplier / notes)" in low:
                send("", echo="(blank)")
                consume_prompt()
                continue

            # mid-batch hardware failure: do NOT blindly continue -> abort safely
            if "reset the system and type 'continue'" in low:
                log("!! app reported a mid-assembly failure. Aborting batch (safe default).")
                send("", echo="(abort)")
                phase = 2
                consume_prompt()
                continue

            # back at the main menu after we've done our work -> quit
            if phase == 2 and ":>" in buf and "welcome to batterylab" in low:
                send("", echo="[Enter] quit")
                consume_prompt()
                break

        # drain any trailing output
        time.sleep(1)
        try:
            while True:
                r, _, _ = select.select([fd], [], [], 1)
                if not r:
                    break
                chunk = os.read(fd, 4096)
                if not chunk:
                    break
                text = chunk.decode(errors="replace")
                sys.stdout.write(text); app_log.write(text)
        except OSError:
            pass
    finally:
        try:
            os.close(fd)
        except OSError:
            pass
        # reap
        try:
            os.waitpid(pid, os.WNOHANG)
        except OSError:
            pass
    log("app driver finished.")


def main():
    log("=== BatteryLab one-click runner: %s ===" % RECIPE_STEM)
    log("logs -> %s" % LOG_DIR)
    log("env: source %s ; ROS_DOMAIN_ID=%s" % (CONFIG["env_setup"], CONFIG["ros_domain_id"]))

    # sanity: env bootstrap present?
    if not Path(expand(CONFIG["env_setup"])).exists():
        log("WARNING: env_setup '%s' not found. ros2 commands will likely fail." % CONFIG["env_setup"])
        log("         Edit lab_config.json (env_setup / extra_source) and re-generate.")

    recipe_path = write_recipe()

    if not check_inventory():
        log("=== aborted: inventory preflight failed. Nothing was launched. ===")
        return 2

    log("--- bringing up ROS2 services ---")
    for spec in CONFIG["launches"]:
        start_launch(spec["role"], spec["host"], spec["cmd"])

    wait_for_nodes()

    log("--- driving the assembly app ---")
    try:
        drive_app(recipe_path)
    except Exception as e:
        log("ERROR while driving the app: %s" % e)
        log("Services are still up so you can take over manually with: %s" % CONFIG["app_cmd"])
        # Do NOT tear down on error -- let the operator inspect / finish by hand.
        atexit.unregister(_terminate_all)
        MAIN_LOG.flush()
        input("\nPress Enter to shut the ROS2 services down and exit... ")
        _terminate_all()
        return 1

    log("=== run complete. Shutting services down. ===")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        log("interrupted by operator.")
        sys.exit(130)
